# Generated by Django 4.2.7 on 2023-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_full_name_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='https://images.freeimages.com/images/large-previews/e04/tibetan-terrier-dog-2-1337950.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
