FROM python:alpine3.17

WORKDIR /server

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev

RUN pip install --upgrade pip

COPY ./requirements.txt /
COPY ./entrypoint-dev.sh /

RUN pip install -r /requirements.txt

COPY ./server/ .

ENTRYPOINT ["/entrypoint-dev.sh"]