version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - ./server/:/server/
    ports:
      - "8001:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  
volumes:
  postgres_data:
