# Generated by Django 4.2.7 on 2023-11-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyStaus',
            new_name='PropertyStatus',
        ),
        migrations.RenameField(
            model_name='propertytype',
            old_name='type',
            new_name='property_type',
        ),
    ]
