# Generated by Django 4.2.7 on 2023-11-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('properites', '0002_rename_propertystaus_propertystatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localarea',
            name='local_level',
        ),
        migrations.RemoveField(
            model_name='locallevel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertylocation',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyprice',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertystatus',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ManyToManyField(to='properites.propertyimage'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_price',
            field=models.ManyToManyField(to='properites.propertyprice'),
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.district'),
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='local_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.localarea'),
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='local_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.locallevel'),
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.province'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='LocalArea',
        ),
        migrations.DeleteModel(
            name='LocalLevel',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
