# Generated by Django 4.2.7 on 2023-11-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properites', '0003_remove_localarea_local_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='properites.propertylocation'),
            preserve_default=False,
        ),
    ]
