# Generated by Django 4.2.7 on 2023-11-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properites', '0005_property_property_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Avaliable'), ('RENTED', 'Rented')], default='AVAILABLE')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_status',
        ),
        migrations.DeleteModel(
            name='PropertyStatus',
        ),
        migrations.AddField(
            model_name='property',
            name='record',
            field=models.ManyToManyField(to='properites.record'),
        ),
    ]
