# Generated by Django 4.2.7 on 2023-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properites', '0007_remove_record_end_date_alter_record_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='no_bedrooms',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.ManyToManyField(db_index=True, to='properites.propertyprice'),
        ),
        migrations.AlterField(
            model_name='property',
            name='record',
            field=models.ManyToManyField(db_index=True, to='properites.record'),
        ),
    ]
