# Use Node.js version 21 based on Alpine Linux
FROM node:21-bullseye-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Set environment variables if needed
ENV NODE_ENV=development

# Expose the port the app runs on
EXPOSE 3000

# Define the command to start the application
CMD ["npm", "run", "dev"]
